--INSERT PRODUTO
MERGE INTO PRODUTO ( IDPROD, DESPROD,   STATUS, VALUNIT) KEY (IDPROD) 
			VALUES ( 1, 'Salad Bacon', 'S', 23.00);

MERGE INTO PRODUTO ( IDPROD, DESPROD,   STATUS, VALUNIT) KEY (IDPROD) 
			VALUES ( 2, 'Xamego Limão 3lts', 'N', 3.00);			
			
--INSERT USUARIO
MERGE INTO USUARIO  ( NICKUSR,           CPFCNPJ,	      CEPUSR,	                      ENDUSR,	NUMENDUSR,	                  EMAILUSR,	  		TELUSR,	SENHA,	                   NOME,              ULTACESSO, TIPUSR ) 
KEY (NICKUSR) VALUES(	'ADM',	'00000000000000',	'0000000000',	'AV. CARLOS REINALDO MENDES',	   '2015',	'FABRICIOH.SILVA@LIVE.COM',	'999999999999',	'ADM',	'USUÁRIO ADMINISTRADOR',	CURRENT_TIMESTAMP(),    'A' );